background = #12275E
foreground = #DCE8FF
cursor-color = #F4F7FF
selection-background = #0000F2
selection-foreground = #F4F7FF
palette = 0=#12275E
palette = 1=#C35871
palette = 2=#5DB3A2
palette = 3=#B8895D
palette = 4=#6C84E8
palette = 5=#6D83D7
palette = 6=#62B4C6
palette = 7=#DCE8FF
palette = 8=#46639A
palette = 9=#EB8195
palette = 10=#86D3BE
palette = 11=#D9B88A
palette = 12=#9FB7FF
palette = 13=#BFC5FF
palette = 14=#8BD6E5
palette = 15=#F4F7FF
