# Nous Research — compositor surface
general {
    col.active_border = rgb(0000f2)
    col.inactive_border = rgba(46639a88)
    border_size = 2
    gaps_in = 8
    gaps_out = 18
}

group {
    col.border_active = rgb(0000f2)
    col.border_inactive = rgba(46639a88)
}

decoration {
    rounding = 2
    rounding_power = 2
    active_opacity = 1.0
    inactive_opacity = 0.98
    shadow {
        enabled = true
        range = 18
        render_power = 3
        color = rgba(0000f233)
        color_inactive = rgba(12275e1c)
    }
}
